import type { IntakeQuestion, QuestionMapping } from "@/lib/questions";

export const mockQuestions: IntakeQuestion[] = [
  {
    id: "q1",
    field_name: "listedWithAgent",
    question_type: "choice",
    question_text: "Is your property listed with an agent?",
    helper_text: null,
    placeholder: null,
    options: ["Yes", "No"],
    is_active: true,
    display_order: 1,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q2",
    field_name: "propertyType",
    question_type: "choice",
    question_text: "What type of property is it?",
    helper_text: null,
    placeholder: null,
    options: ["Single Family", "Multi Family", "Condo", "Townhouse", "Vacant Land"],
    is_active: true,
    display_order: 2,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q3",
    field_name: "ownsLand",
    question_type: "choice",
    question_text: "Do you own the land?",
    helper_text: null,
    placeholder: null,
    options: ["Yes", "No"],
    is_active: true,
    display_order: 3,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q4",
    field_name: "repairsNeeded",
    question_type: "choice",
    question_text: "What repairs are needed?",
    helper_text: null,
    placeholder: null,
    options: [
      "Move-In Ready - No Repairs",
      "Cosmetic Work $ - Flooring, Paint",
      "Minor Renovations $$ - Kitchen, Bathroom, Roof",
      "Major Repairs $$$ - Foundation, Structural, Extensive Damage",
    ],
    is_active: true,
    display_order: 4,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q5",
    field_name: "closeTimeline",
    question_type: "choice",
    question_text: "When do you need to close?",
    helper_text: null,
    placeholder: null,
    options: ["ASAP (7-14 Days)", "30-60 Days", "60-90 Days", "Flexible"],
    is_active: true,
    display_order: 5,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q6",
    field_name: "sellReason",
    question_type: "choice",
    question_text: "Why are you selling?",
    helper_text: null,
    placeholder: null,
    options: [
      "Downsizing",
      "Inherited",
      "Relocation",
      "Divorce",
      "Financial Hardship",
      "Other",
    ],
    is_active: true,
    display_order: 6,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q7",
    field_name: "acceptableOffer",
    question_type: "text",
    question_text: "What offer would you accept?",
    helper_text: null,
    placeholder: "$250,000",
    options: null,
    is_active: true,
    display_order: 7,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q8",
    field_name: "streetAddress",
    question_type: "address",
    question_text: "What is the property address?",
    helper_text: null,
    placeholder: null,
    options: null,
    is_active: true,
    display_order: 8,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q9",
    field_name: "fullName",
    question_type: "contact",
    question_text: "How can we reach you?",
    helper_text: null,
    placeholder: null,
    options: null,
    is_active: true,
    display_order: 9,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

export const mockMappings: QuestionMapping[] = [
  {
    id: "m1",
    from_question_id: "q1",
    answer_value: null,
    to_question_id: "q2",
    redirect_url: null,
    priority: 1,
    is_active: true,
    conditional_logic: null,
    conditional_to_question_id: null,
    conditional_redirect_url: null,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "m2",
    from_question_id: "q2",
    answer_value: null,
    to_question_id: "q3",
    redirect_url: null,
    priority: 1,
    is_active: true,
    conditional_logic: null,
    conditional_to_question_id: null,
    conditional_redirect_url: null,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "m3",
    from_question_id: "q3",
    answer_value: null,
    to_question_id: "q4",
    redirect_url: null,
    priority: 1,
    is_active: true,
    conditional_logic: null,
    conditional_to_question_id: null,
    conditional_redirect_url: null,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "m4",
    from_question_id: "q4",
    answer_value: null,
    to_question_id: "q5",
    redirect_url: null,
    priority: 1,
    is_active: true,
    conditional_logic: null,
    conditional_to_question_id: null,
    conditional_redirect_url: null,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "m5",
    from_question_id: "q5",
    answer_value: null,
    to_question_id: "q6",
    redirect_url: null,
    priority: 1,
    is_active: true,
    conditional_logic: null,
    conditional_to_question_id: null,
    conditional_redirect_url: null,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "m6",
    from_question_id: "q6",
    answer_value: null,
    to_question_id: "q7",
    redirect_url: null,
    priority: 1,
    is_active: true,
    conditional_logic: null,
    conditional_to_question_id: null,
    conditional_redirect_url: null,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "m7",
    from_question_id: "q7",
    answer_value: null,
    to_question_id: "q8",
    redirect_url: null,
    priority: 1,
    is_active: true,
    conditional_logic: null,
    conditional_to_question_id: null,
    conditional_redirect_url: null,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "m8",
    from_question_id: "q8",
    answer_value: null,
    to_question_id: "q9",
    redirect_url: null,
    priority: 1,
    is_active: true,
    conditional_logic: null,
    conditional_to_question_id: null,
    conditional_redirect_url: null,
    deleted_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

export const mockQuestionsResponse = {
  questions: mockQuestions,
  mappings: mockMappings,
};
